// <auto-generated />
namespace WebBanHaiSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Table_Review_Edit_ForeignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_Review_Edit_ForeignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202312171733387_Table_Review_Edit_ForeignKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
